/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useEffect, useState } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export default function Model({ ...props }) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("/chicken.glb");
  const { actions } = useAnimations(animations, group);

  const [position, setPosition] = useState({
    x: 0.04,
    y: 0.41,
    z: 0.16,
    r: 0,
  });

  useEffect(() => {
    if (!props.play) actions.Flapping.stop();
    else actions.Flapping.play();
  }, [props.play]);

  useEffect(() => {
    const setPoint = (event) => {
      if (props.selected !== "chicken") {
        setPosition(position);
        return;
      }

      switch (event.keyCode) {
        case 101:
          setPosition({
            x: position.x,
            y: position.y,
            z: position.z,
            r: position.r + 1,
          });
          return;
        case 113:
          setPosition({
            x: position.x,
            y: position.y,
            z: position.z,
            r: position.r - 1,
          });
          return;
        case 119:
          setPosition({
            x: position.x,
            y: position.y + 1,
            z: position.z,
            r: position.r,
          });
          return;
        case 115:
          setPosition({
            x: position.x,
            y: position.y - 1,
            z: position.z,
            r: position.r,
          });
          return;
        case 100:
          setPosition({
            x: position.x + 1,
            y: position.y,
            z: position.z,
            r: position.r,
          });
          return;
        case 97:
          setPosition({
            x: position.x - 1,
            y: position.y,
            z: position.z,
            r: position.r,
          });
          return;
        case 122:
          setPosition({
            x: position.x,
            y: position.y,
            z: position.z + 1,
            r: position.r,
          });
          return;
        case 120:
          setPosition({
            x: position.x,
            y: position.y,
            z: position.z - 1,
            r: position.r,
          });
          return;
      }
    };

    window.addEventListener("keypress", setPoint);
  }, [props.selected, position]);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group
          name="Armature"
          position={[position.x, position.y, position.z]}
          rotation={[-Math.PI, position.r, -Math.PI]}
          scale={0.5}
        >
          <group
            name="Bone001"
            position={[0.03, -0.06, -0.02]}
            rotation={[0, 0, -0.01]}
          >
            <group
              name="Bone002"
              position={[0, 1.23, 0]}
              rotation={[-1.55, 0.32, 0.01]}
            >
              <group
                name="Bone004"
                position={[0, 0.86, 0]}
                rotation={[1.53, -0.02, -0.02]}
              />
              <mesh
                name="Cube"
                geometry={nodes.Cube.geometry}
                material={materials.Material}
                position={[0.02, 0.53, 0.56]}
                scale={0.63}
              >
                {props.wireframe && (
                  <meshBasicMaterial
                    attach="material"
                    color="hotpink"
                    wireframe
                  />
                )}
              </mesh>
            </group>
            <group
              name="Bone006"
              position={[0.44, -0.06, 0.01]}
              rotation={[1.57, -1.57, -2.15]}
            >
              <mesh
                name="Cube002"
                geometry={nodes.Cube002.geometry}
                material={materials.Material}
                position={[-0.02, -0.2, 0.12]}
                rotation={[Math.PI, -1.57, 0]}
                scale={[0.27, 0.5, 0.26]}
              >
                {props.wireframe && (
                  <meshBasicMaterial
                    attach="material"
                    color="hotpink"
                    wireframe
                  />
                )}
              </mesh>
            </group>
            <group
              name="Bone008"
              position={[-0.38, -0.07, 0.02]}
              rotation={[1.57, -1.57, -1]}
            >
              <mesh
                name="Cube008"
                geometry={nodes.Cube008.geometry}
                material={materials.Material}
                position={[-0.02, -0.23, -0.11]}
                rotation={[Math.PI, -1.57, 0]}
                scale={[0.27, 0.5, 0.26]}
              >
                {props.wireframe && (
                  <meshBasicMaterial
                    attach="material"
                    color="hotpink"
                    wireframe
                  />
                )}
              </mesh>
            </group>
            <group
              name="Bone_shoulde_left"
              position={[0, 1.23, 0]}
              rotation={[-1.88, -0.03, 1.56]}
            >
              <group
                name="Bone010"
                position={[-0.02, 0.93, -0.01]}
                rotation={[-0.27, -0.3, -0.08]}
              >
                <mesh
                  name="Cube005"
                  geometry={nodes.Cube005.geometry}
                  material={materials.Material}
                  position={[0.01, -0.13, -0.16]}
                  rotation={[0.92, -1.57, -1.72]}
                  scale={[0.43, 0.5, 2.04]}
                >
                  {props.wireframe && (
                    <meshBasicMaterial
                      attach="material"
                      color="hotpink"
                      wireframe
                    />
                  )}
                </mesh>
              </group>
            </group>
            <group
              name="_Bone_Shoulder_right"
              position={[0, 1.23, 0]}
              rotation={[-1.86, -0.03, -1.58]}
            >
              <group
                name="Bone003"
                position={[0.06, 0.98, -0.05]}
                rotation={[2.1, -0.15, 2.9]}
              >
                <mesh
                  name="Cube004"
                  geometry={nodes.Cube004.geometry}
                  material={materials.Material}
                  position={[-0.04, -0.16, 0.27]}
                  rotation={[-2.55, -Math.PI / 2, 0]}
                  scale={[0.51, 0.5, 2.04]}
                >
                  {props.wireframe && (
                    <meshBasicMaterial
                      attach="material"
                      color="hotpink"
                      wireframe
                    />
                  )}
                </mesh>
              </group>
            </group>
            <mesh
              name="Cube001"
              geometry={nodes.Cube001.geometry}
              material={materials.Material}
              position={[-0.01, 0.79, 0.02]}
              scale={[1, 0.64, 2.91]}
            >
              {props.wireframe && (
                <meshBasicMaterial
                  attach="material"
                  color="hotpink"
                  wireframe
                />
              )}
            </mesh>
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/chicken.glb");
