/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useEffect } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export default function Model({ ...props }) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("/ender.glb");
  const { actions } = useAnimations(animations, group);

  useEffect(() => {
    if (!props.play) actions.Swinging.stop();
    else actions.Swinging.play();
  }, [props.play]);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Armature" position={[-3, 2.2, -2]} scale={0.44}>
          <group name="Bone001" position={[0.03, -0.02, -0.02]}>
            <group
              name="Bone002"
              position={[0, 2.28, 0]}
              rotation={[-0.02, 0.68, 0.02]}
            >
              <mesh
                name="Cube"
                geometry={nodes.Cube.geometry}
                material={materials.Material}
                position={[0, 0.1, 0.02]}
              />
            </group>
            <group
              name="Bone006"
              position={[0.44, -0.24, 0.01]}
              rotation={[1.57, -1.57, -1.57]}
            >
              <mesh
                name="Cube002"
                geometry={nodes.Cube002.geometry}
                material={materials.Material}
                position={[-0.02, 0.15, 0.17]}
                rotation={[Math.PI, -1.57, 0]}
                scale={[0.41, 1.77, 0.37]}
              />
            </group>
            <group
              name="Bone008"
              position={[-0.38, -0.25, 0.02]}
              rotation={[1.57, -1.57, -1.58]}
            >
              <mesh
                name="Cube008"
                geometry={nodes.Cube008.geometry}
                material={materials.Material}
                position={[-0.02, 0.15, -0.18]}
                rotation={[Math.PI, -1.57, 0]}
                scale={[0.44, 1.76, 0.4]}
              />
            </group>
            <group
              name="Bone_shoulde_left"
              position={[0, 2.28, 0]}
              rotation={[-1.89, -0.3, 1.48]}
            >
              <group
                name="Bone010"
                position={[0.01, 0.98, -0.02]}
                rotation={[-0.8, -0.22, -0.22]}
              >
                <mesh
                  name="Cube005"
                  geometry={nodes.Cube005.geometry}
                  material={materials.Material}
                  position={[-0.04, 0.34, -0.09]}
                  rotation={[Math.PI, -1.57, 0]}
                  scale={[0.41, 1.81, 0.36]}
                />
              </group>
            </group>
            <group
              name="_Bone_Shoulder_right"
              position={[0, 2.28, 0]}
              rotation={[-1.86, 0.27, -1.49]}
            >
              <group
                name="Bone003"
                position={[0, 1.03, -0.04]}
                rotation={[2.38, -0.21, 2.95]}
              >
                <mesh
                  name="Cube004"
                  geometry={nodes.Cube004.geometry}
                  material={materials.Material}
                  position={[-0.02, 0.35, 0.17]}
                  rotation={[Math.PI, -1.57, 0]}
                  scale={[0.42, 1.81, 0.35]}
                />
              </group>
            </group>
            <mesh
              name="Cube001"
              geometry={nodes.Cube001.geometry}
              material={materials.Material}
              position={[0, 1.14, 0.02]}
            />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/ender.glb");
