/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model({ ...props }) {
  const group = useRef();
  const { nodes, materials } = useGLTF("/tree.glb");
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        geometry={nodes.Tree.geometry}
        material={materials.Material}
        position={[4, 1.8, -1.5]}
        scale={[0.14, 0.68, 0.14]}
      >
        {props.wireframe && (
          <meshBasicMaterial attach="material" color="hotpink" wireframe />
        )}
      </mesh>
    </group>
  );
}

useGLTF.preload("/tree.glb");
