/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model({ ...props }) {
  const group = useRef();
  const { nodes, materials } = useGLTF("/tree.glb");
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        geometry={nodes.Tree.geometry}
        material={materials.Material}
        position={[-1, 2.3, -4]}
        scale={[0.3, 2.2, 0.14]}
      />
    </group>
  );
}

useGLTF.preload("/tree.glb");
