/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useEffect } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export default function Model({ ...props }) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("/creeper3.glb");
  const { actions } = useAnimations(animations, group);

  useEffect(() => {
    if (!props.play) actions.ArmatureAction.stop();
    else actions.ArmatureAction.play();
  }, [props.play]);

  console.log(actions);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Armature" position={[0.04, 1.11, 0.16]} scale={0.44}>
          <group name="Bone001" position={[0.03, -0.02, -0.02]}>
            <group
              name="Bone002"
              position={[0, 2.32, 0]}
              rotation={[-0.56, 0.03, -2.19]}
            >
              <mesh
                name="Cube"
                geometry={nodes.Cube.geometry}
                material={materials.Material}
                position={[0, 0.06, 0.02]}
              />
            </group>
            <group
              name="Bone006"
              position={[2.08, -2.2, 0.28]}
              rotation={[Math.PI, -Math.PI / 2, 0]}
            >
              <group
                name="Bone007"
                position={[0, 0.98, 0]}
                rotation={[-0.05, -0.07, 0.05]}
              >
                <mesh
                  name="Cube009"
                  geometry={nodes.Cube009.geometry}
                  material={materials.Material}
                  position={[-0.04, 1.03, -0.35]}
                  rotation={[0, -Math.PI / 2, 0]}
                  scale={[1, 0.5, 1]}
                />
              </group>
              <mesh
                name="Cube002"
                geometry={nodes.Cube002.geometry}
                material={materials.Material}
                position={[-0.02, -0.02, 0.44]}
                rotation={[Math.PI, -1.57, 0]}
                scale={[1, 0.5, 1]}
              />
            </group>
            <group
              name="Bone008"
              position={[-1.07, -2.48, 0.65]}
              rotation={[Math.PI, -Math.PI / 2, 0]}
            >
              <group
                name="Bone009"
                position={[0, 0.98, 0]}
                rotation={[0.01, -0.03, -0.1]}
              >
                <mesh
                  name="Cube003"
                  geometry={nodes.Cube003.geometry}
                  material={materials.Material}
                  position={[0.38, 1.04, 0.04]}
                  scale={[1, 0.5, 1]}
                />
              </group>
              <mesh
                name="Cube008"
                geometry={nodes.Cube008.geometry}
                material={materials.Material}
                position={[-0.02, -0.02, -0.36]}
                rotation={[Math.PI, -1.57, 0]}
                scale={[1, 0.5, 1]}
              />
            </group>
            <group
              name="Bone_shoulde_left"
              position={[0, 2.32, 0]}
              rotation={[-1.89, -0.3, 1.48]}
            >
              <group
                name="Bone010"
                position={[-0.67, 3.91, -1.53]}
                rotation={[-1.28, -0.09, -0.29]}
              >
                <group
                  name="Bone011"
                  position={[0, 0.83, 0]}
                  rotation={[0.04, -0.02, 0.07]}
                >
                  <mesh
                    name="Cube006"
                    geometry={nodes.Cube006.geometry}
                    material={materials.Material}
                    position={[0.39, 0.96, 0.1]}
                    scale={[1, 0.5, 1]}
                  />
                </group>
                <mesh
                  name="Cube005"
                  geometry={nodes.Cube005.geometry}
                  material={materials.Material}
                  position={[-0.02, -0.21, -0.3]}
                  rotation={[Math.PI, -1.57, 0]}
                  scale={[1, 0.5, 1]}
                />
              </group>
            </group>
            <group
              name="_Bone_Shoulder_right"
              position={[0, 2.32, 0]}
              rotation={[-1.86, 0.27, -1.49]}
            >
              <group
                name="Bone003"
                position={[-0.23, 4.58, -1.68]}
                rotation={[1.84, -0.08, 2.87]}
              >
                <group name="Bone004" position={[0, 0.79, 0]}>
                  <mesh
                    name="Cube007"
                    geometry={nodes.Cube007.geometry}
                    material={materials.Material}
                    position={[-0.41, 0.94, 0.01]}
                    scale={[1, 0.5, 1]}
                  />
                </group>
                <mesh
                  name="Cube004"
                  geometry={nodes.Cube004.geometry}
                  material={materials.Material}
                  position={[-0.02, -0.25, 0.4]}
                  rotation={[Math.PI, -1.57, 0]}
                  scale={[1, 0.5, 1]}
                />
              </group>
            </group>
            <mesh
              name="Cube001"
              geometry={nodes.Cube001.geometry}
              material={materials.Material}
              position={[0, 1.18, 0.02]}
            />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/creeper3.glb");
