/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useEffect } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export default function Model({ ...props }) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("/lego.glb");
  const { actions } = useAnimations(animations, group);

  useEffect(() => {
    if (!props.play) actions["0Action"].stop();
    else actions["0Action"].play();
  }, [props.play]);

  console.log(actions);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Armature" position={[3, 0, -0.15]}>
          <primitive object={nodes.Root} />
          <primitive object={nodes.Root008} />
          <primitive object={nodes.Root009} />
          <skinnedMesh
            name="Lego1"
            geometry={nodes.Lego1.geometry}
            material={materials.Material}
            skeleton={nodes.Lego1.skeleton}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/lego.glb");
